### ISSUE TITLE
About Tusimple test dataset

### ISSUE THREAD

**Issue by pikaqiu-wpc** [fabvio/Cascade-LD#7]
Hello, thank you very much for publishing the lane category of the Tusimple train data, which is of great help to my experiment. Could you please publish the category of the Tusimple test set?

**Comment by fabvio** [comment]
Hi, I'm glad you found them useful. At the time (Aug 2018) it was not possible for me to annotate the TuSimple test set since it was a challenge and it was not public. Recently, TuSimple has published the entire dataset in a GitHub issue, as I linked. So, I don't have the labels yet, but you can annotate them really easily. I remember that the whole annotation process took like 2 days for the trainval. The annotator I used is not so in good shape to be shared, but you can easily modify the visualizer.py code to build an annotator if needed. You can contact me privately for tips on this if you need them.
